services:
  cdn:
    image: caddy:2.10.2-alpine
    container_name: cdn-optimizemefy-caddy
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv:ro
    networks:
      ghost_network:
        aliases:
          - cdn

networks:
  ghost_network:
    external: true